require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/listings', type: :request do
  # Test suite for GET /listings test :title :details :date and :time
  # create test user
  let!(:user) { create(:user) }
  # set headers for authorization
  let(:headers) { valid_headers }

  # define listing_id from user
  let!(:listings) { create(:listing, user_id: user.id) }
  let!(:listing_id) { listings.id }

  # Test suite for GET /listings
  let(:valid_headers) do
    {
      'Authorization' => token_generator(user.id)
    }
  end

  describe 'GET /listings' do
    # make HTTP get request before each example
    before { get '/listings', params: {}, headers: headers }

    it 'returns status code 200' do
      expect(response).to have_http_status(200)
    end
  end
end
